### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by ecrisost** [CMPT-275-Group-13/lucky13#22]
User will be able to search for a patient in the database

**Comment by ecrisost** [comment]
I did some investigation and Firestore doesn't have the ability for a full text search without the use of a third party software (Algolia). So at the moment, with the search I've implemented, the user has to enter the text as is to populate results (ie: enter "chelsie" as oppose to "ch").

**Comment by cjinn** [comment]
Reviewed feature and approved. Closing issue
